version: "3.8"

services:
  dev_server:
    image: zeeguu/api
    environment:
      ZEEGUU_CONFIG: /Zeeguu-API/default_docker.cfg
      ZEEGUU_ES_CONN_STRING: "elasticsearch:9200"
      PYTHONUNBUFFERED: 1
      MICROSOFT_TRANSLATE_API_KEY: ${MICROSOFT_TRANSLATE_API_KEY}
      GOOGLE_TRANSLATE_API_KEY: ${GOOGLE_TRANSLATE_API_KEY}

    ports:
      - 9001:9001
    volumes:
      - .:/Zeeguu-API
      - ./data/zeeguu:/zeeguu-data
    entrypoint: "python /Zeeguu-API/start.py"
    networks:
      - zeeguu_backend
    depends_on:
      - elasticsearch

  readability_server:
    image: zeeguu/readability_server
    ports:
      - 3456:3456
    networks:
      - zeeguu_backend
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:7.6.2
    platform: linux/amd64
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0 # is this still needed? 
    volumes:
      - ./data/elasticsearch_db/data:/usr/share/elasticsearch/data
    networks:
      - zeeguu_backend
    restart: unless-stopped



  dev_play:
    image: zeeguu/api
    environment:
      ZEEGUU_CONFIG: /Zeeguu-API/default_docker.cfg

    volumes:
      - .:/Zeeguu-API
      - ./data/zeeguu:/zeeguu-data
    entrypoint: "python tools/_playground.py"
    networks:
      - zeeguu_backend

  # docker-compose run --rm dev_bash
  dev_bash:
    image: zeeguu/api
    stdin_open: true # docker run -i
    tty: true # docker run -t

    environment:
      ZEEGUU_CONFIG: /Zeeguu-API/default_docker.cfg

    volumes:
      - .:/Zeeguu-API
      - ./data/zeeguu:/zeeguu-data
    entrypoint: "bash"
    networks:
      - zeeguu_backend

  dev_test:
    image: zeeguu/api
    environment:
      ZEEGUU_CONFIG: /Zeeguu-API/default_docker.cfg

    volumes:
      - .:/Zeeguu-API
      - ./data/zeeguu:/zeeguu-data
    entrypoint: "./run_tests.sh"
    networks:
      - zeeguu_backend

  dev_init_es:
    image: zeeguu/api
    environment:
      ZEEGUU_CONFIG: /Zeeguu-API/default_docker.cfg
      ZEEGUU_ES_CONN_STRING: "elasticsearch:9200"

    volumes:
      - .:/Zeeguu-API
      - ./data/zeeguu:/zeeguu-data
      - /Users:/userslalal
    entrypoint: "python tools/mysql_to_elastic.py"
    networks:
      - zeeguu_backend
    depends_on:
      - elasticsearch


networks:
  zeeguu_backend:
